name: Daily Vercel Rebuild

on:
  schedule:
    # Runs at 00:00 UTC (3:00 AM Bulgarian Time) every day
    - cron: '0 0 * * *'
  
  # Allows you to trigger it manually from the GitHub Actions tab if needed
  workflow_dispatch:

jobs:
  rebuild:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Vercel Deploy Hook
        run: curl -X POST "https://api.vercel.com/v1/integrations/deploy/prj_Q5zCzwGqKpJ3jVQu4HLurDMY3f8B/PvEDo4Vhh6"
